### ISSUE TITLE
Instances won't receive ssh connections after being up for a day

### ISSUE THREAD

**Issue by land-fish** [edurange/edurange-server#23]
In ssh_inception, total_recon (the only two I have tested), the instances (except the NAT), will no longer receive ssh connections. Nmap shows that port 22 is open, but connections attempt always hang before login information is requested. A similar ssh-freeze happens when running tmux and existing badly. There doesn't appear to be an unusual amount of network traffic or processor use. I'm unsure what is causing this.

**Comment by newjam** [comment]
I haven't heard anyone complain about this recently, so hopefully it is no longer an issue.
