### ISSUE TITLE
Some S3 Buckets are too large to save when destroying a scenario

### ISSUE THREAD

**Issue by land-fish** [edurange/edurange-server#24]
Only observed on my development server. The S3 files from script logs on instances in total recon (usually mars_aerospace_port) became very large, like 30 MB or more. I have fixed the code that caused the excessively large log files, although files of this size will sometimes be generated due to user behaviour (commands with lots of output causes large script files). When scenarios are destroyed, this data is saved in files in /edurange-server/data/statistics . Currently, it is also printing the whole script log to the server log (was for debugging), which it should not do! I will fix this soon.

**Comment by newjam** [comment]
We currently do not collect terminal output (although this is in the works, issue https://github.com/edurange/edurange-server/issues/41 should be the location for this).
